# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1465247b62bd17ea23d5204200fef48dee360083d9280f7d542da5e93cdf37f586dee25fcdb0d71891d4d275de202f1ebb35f252e266f7b4138fb44dfdf96db0

test:
  secret_key_base: b286aee079de35f4a65365f4ad6ad3cd87707468e90136c482ff2211be2a0c6acf4ebcc4c55126327c2fc590cd6e0e6d38c9aec3bd51fabb5ef7f512a8913511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
